### ISSUE TITLE
[SV]:Use epoll mode to implement a simple IO-Server

### ISSUE THREAD

**Issue by aishenhaowe** [aishenhaowe/futurecity#19]

**Comment by aishenhaowe** [comment]
Use select poll mode to implement a simple IO-Server which can receive the data from endpoints and can send data to the endpoints also :-)

**Comment by aishenhaowe** [comment]
1. Can receive data from device, device-emulation or some other tools
2. Can show the data received in shell and save all of the data into a log file, think we should include a open source log system into the project
3. Maybe a loop back is also needed for us, this will be used for debug. the device will know whether it connect success or not :-)

@lihaoran123 Are you interested in this story, if so, I can assign it to you?

**Comment by hipsonlee** [comment]
I'm pleased to accpt the assign that the us gives to me.

**Comment by aishenhaowe** [comment]
Should add a connection pool now to manage all of the connections :-)

**Comment by aishenhaowe** [comment]
We need some classes for the connections. Client can send and receive messages through these connections directly :-)

**Comment by aishenhaowe** [comment]
OuterConnection class is needed now :-)

**Comment by aishenhaowe** [comment]
It's difficult to maintain, so close it.
We should create some much smaller story to develop it :-)
